defaults:
  - model_checkpoint.yaml
#  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/cd"
  mode: "min"
  save_last: True
  save_top_k: 3
  auto_insert_metric_name: False

#early_stopping:
#  monitor: "val/acc"
#  patience: 100
#  mode: "max"

model_summary:
  max_depth: 3
